IMSApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IMSApp.Data;
using IMSApp.Models;

namespace IMSApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Orders.Include(o => o.Product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Product)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

IMSApp/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IMSApp.Data;
using IMSApp.Models;

namespace IMSApp.Controllers
{
    public class SalesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SalesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sales
        public async Task<IActionResult> Index()
        {
            var totalSales = await _context.Sales.SumAsync(s => s.TotalAmount);
            var salesByBrandCategoryOrderDate = await _context.Sales
            .Include(s => s.Order)
            .ThenInclude(o => o.Product)
            .ThenInclude(p => p.Category)
            .Select(s => new
            {
                Brand = s.Order.Product.Brand,
                Category = s.Order.Product.Category.Name,
                TotalAmount = s.TotalAmount
             })
            .ToListAsync();

            ViewBag.TotalSales = totalSales;
            ViewBag.SalesByBrandCategoryOrderDate = salesByBrandCategoryOrderDate;

            var applicationDbContext = _context.Sales.Include(s => s.Order);
            return View(await applicationDbContext.ToListAsync());
        }

        
    }
}

IMSApp/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IMSApp.Data;
using IMSApp.Models;

namespace IMSApp.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SuppliersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Suppliers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Suppliers.ToListAsync());
        }

        // GET: Suppliers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SupplierId,Name,ContactInfo,Address")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SupplierId,Name,ContactInfo,Address")] Supplier supplier)
        {
            if (id != supplier.SupplierId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.SupplierId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier != null)
            {
                _context.Suppliers.Remove(supplier);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(int id)
        {
            return _context.Suppliers.Any(e => e.SupplierId == id);
        }
    }
}

IMSApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>ApnaMobile.com</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] - ApnaMobile.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IMSApp.styles.css" asp-append-version="true" />
    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/css/responsive.css">
   
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
        <!-- loader  -->
        <div class="loader_bg">
        <div class="loader"><img src="~/images/loading.gif" alt="#" /></div>
        </div>
        <!-- end loader -->
        <!-- header -->
        <header>
            <!-- header inner -->
            <div class="header">
            <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                    <div class="full">
                        <div class="center-desk">
                                <div> <a style="font-size:30px; color:red;" asp-controller="Home" asp-action="Index">ApnaMobile.com</a> </div>
                        </div>
                    </div>
                </div>
                        <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                            <div class="menu-area">
                                <div class="limit-box">
                                    <nav class="main-menu">
                                        <ul class="menu-area-main">
                                            <li> <a  asp-area="" asp-controller="Home" asp-action="Index">Home</a> </li>
                                            <li> <a  asp-area="" asp-controller="Home" asp-action="BuyNow">Buy Now</a> </li>
                                            <li><a  asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a></li>
                                            <li><a  asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                                        <li>
                                            <a class="dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Account
                                            </a>
                                            <div class="dropdown-menu custom-dropdown-menu" aria-labelledby="navbarDropdown2">
                                                <a style="color:red;" asp-controller="Orders" asp-action="Index">My Orders</a>
                                                <a style="color:red;" asp-controller="Sales" asp-action="Index">Sales Data</a>
                                            </div>
                                        </li>
                                        <li>
                                            <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Edit
                                            </a>
                                            <div class="dropdown-menu"  aria-labelledby="navbarDropdown">
                                                <a style="color:red;" asp-controller="Products" asp-action="Index">Products</a>
                                                <a style="color:red;" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                                            </div>
                                        </li>
                                            
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end header inner -->
        </header>
        <!-- end header -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
   
</body>
<!-- footer -->
<footer style="position:relative;" class="footer">
    
    <div id="contact" >
        <div class="container">
            <div class="row pdn-top-30">
                <div class="col-md-12 ">
                    <div class="footer-box">
                        <div class="headinga">
                            <h3>Address</h3>
                            <span>Ayodhya UP, India</span>
                            <p>
                                (+91) 8429985575
                                <br>apnamobilecare@gmail.com
                            </p>
                        </div>
                        <ul class="location_icon">
                            <li> <a href="#"><i class="fa fa-facebook-f"></i></a></li>
                            <li> <a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li> <a href="#"><i class="fa fa-instagram"></i></a></li>

                        </ul>
                        <div class="menu-bottom">
                            <ul class="link">
                                <li> <a asp-area="" asp-controller="Home" asp-action="Index">Home</a> </li>
                                <li> <a asp-area="" asp-controller="Home" asp-action="BuyNow">Buy Now</a> </li>
                                <li><a asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a></li>
                                <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
            <div class="container">
                &copy; 2024 - IMSApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        
    </div>
</footer>
<!-- end footer -->
<!-- Javascript files-->
<script src="~/js/jquery.min.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.bundle.min.js"></script>
<script src="~/js/jquery-3.0.0.min.js"></script>
<script src="~/js/plugin.js"></script>
<!-- sidebar -->
<script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/js/custom.js"></script>
<!-- javascript -->
<script src="~/js/owl.carousel.js"></script>
<script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
<script>
    $(document).ready(function () {
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });

        $(".zoom").hover(function () {

            $(this).addClass('transition');
        }, function () {

            $(this).removeClass('transition');
        });
    });
</script>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+z8vwu7+OE2Hs/1C+qGQ6P6gYyyKkf0t/xbi1zr"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"
        integrity="sha384-wsiefXQJK8MgSQsHYoqyvIQKj+QiIlitlF4Jzz++PM3oLfN/sSFprI5PKcJfY+t/"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+z8vwu7+OE2Hs/1C+qGQ6P6gYyyKkf0t/xbi1zr"
        crossorigin="anonymous"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>